services:

  mongodb:
    image: mongo:8
    container_name: cognia-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - cognia-mongodb-data:/data/db

  backend:
    build:
      context: ./backend
    container_name: cognia-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      MONGODB_URL: mongodb://mongodb:27017/
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
    container_name: cognia-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  cognia-mongodb-data: